### ISSUE TITLE
Feature request: More height

### ISSUE THREAD

**Issue by tomlut** [bokub/home-assistant-extension#7] opened 2021-05-12 13:36 UTC
Any chance we could get about double the currently available height?

**Comment by bokub** [comment] 2021-05-12 13:39
Not possible because browser limits the height of the extension popup to 600px.

Duplicate of  #3

**Closed by bokub** 2021-05-12 13:39 UTC

**Comment by bokub** [comment] 2021-05-12 13:48
Actually, it looks like I can have an height up to 656 pixels before scrollbar appears.

I'll update the extension with this limit, but you will only gain a few pixels, you cannot double the height

**Comment by tomlut** [comment] 2021-05-12 15:20
No worries. Sorry for not searching the closed issues first.
